import os
files = {
"01-universal": ('<h2>1. Universal Selector (*)</h2><p>Selects all elements. Used for reset.</p><div class="box">Box 1</div><p>Paragraph</p>', '*{margin:0;padding:0;box-sizing:border-box;} body{font-family:Arial;padding:20px;}.box{background:lightblue;padding:20px;margin:10px;border:2px solid blue;}'),
"02-element": ('<h2>2. Element Selector</h2><p>This p is blue</p><h1>This h1 is 24px</h1><p>Another p</p>', 'body{font-family:Arial;padding:20px;} p{color:blue;} h1{font-size:24px;color:red;}'),
"03-class": ('<h2>3. Class Selector (.)</h2><div class="box">Box with class.box</div><div class="box">Another Box</div>', 'body{font-family:Arial;padding:20px;}.box{width:100px;height:100px;background:red;color:white;padding:20px;margin:10px;display:inline-block;}'),
"04-id": ('<h2>4. ID Selector (#)</h2><div id="header">This is #header - ID is unique</div><div class="box">Normal box</div>', 'body{font-family:Arial;padding:20px;} #header{background:black;color:white;padding:20px;font-weight:bold;}.box{background:lightblue;padding:20px;margin-top:10px;}'),
"05-attribute": ('<h2>5. Attribute Selector</h2><input type="text" placeholder="Text input - gray border"><br><br><input type="password" placeholder="Password input"><br><br><input type="text" placeholder="Another text">', 'body{font-family:Arial;padding:20px;} input[type="text"]{border:3px solid gray;padding:10px;} input[type="password"]{border:3px solid red;padding:10px;}'),
"06-descendant": ('<h2>6. Descendant Selector (space)</h2><div class="container"><p>This p inside container is GREEN</p><div><p>This p is also inside container (nested) - also GREEN</p></div></div><p>This p outside container is normal</p>', 'body{font-family:Arial;padding:20px;}.container{background:#f0f0f0;padding:20px;border:2px solid #333;}.container p{color:green;font-weight:bold;}'),
"07-child": ('<h2>7. Child Selector (>)</h2><div class="container"><p>Direct child p - BOLD</p><div><p>Nested p - NOT bold (not direct child)</p></div><p>Another direct child - BOLD</p></div>', 'body{font-family:Arial;padding:20px;}.container{background:#f0f0f0;padding:20px;border:2px solid #333;}.container > p{font-weight:bold;color:blue;border:1px solid blue;}'),
"08-adjacent": ('<h2>8. Adjacent Sibling (+)</h2><h2>Heading H2</h2><p>This p right after H2 - gray and margin 0 (h2 + p)</p><p>This second p is normal</p><h2>Another H2</h2><p>This p is also after H2 - gray</p>', 'body{font-family:Arial;padding:20px;} h2 + p{margin-top:0;color:gray;font-style:italic;border:1px dashed gray;padding:5px;}'),
"09-general": ('<h2>9. General Sibling (~)</h2><h2>Heading H2</h2><p>First p after H2 - ORANGE</p><div>Div between</div><p>Second p after H2 - also ORANGE (general sibling)</p><p>Third p - also ORANGE</p>', 'body{font-family:Arial;padding:20px;} h2 ~ p{color:orange;font-weight:bold;}'),
"10-pseudo-class": ('<h2>10. Pseudo-class (:)</h2><a href="#">Hover over this link - turns RED</a><ul><li>First child - BOLD</li><li>Second item</li><li>Third item</li></ul><input type="text" placeholder="Focus on me">', 'body{font-family:Arial;padding:20px;} a:hover{color:red;font-size:20px;} li:first-child{font-weight:bold;background:yellow;} input:focus{border:3px solid blue;outline:none;}'),
"11-pseudo-element": ('<h2>11. Pseudo-element (::)</h2><p class="first-line">This paragraph first line is bold. Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p><p class="before">This paragraph has star before it using ::before</p>', 'body{font-family:Arial;padding:20px;} p.first-line::first-line{font-weight:bold;color:blue;} p.before::before{content:"★ ";color:gold;font-size:20px;} p.before::after{content:" - After";color:red;}'),
}
for folder,(body,css) in files.items():
    os.makedirs(folder, exist_ok=True)
    html = f"<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>{folder}</title><link rel='stylesheet' href='style.css'></head><body>{body}</body></html>"
    open(f"{folder}/index.html","w",encoding="utf-8").write(html)
    open(f"{folder}/style.css","w",encoding="utf-8").write(f"body{{font-family:sans-serif}}{css}")
print("Q3 - 11 Selectors folders done!")