import os
data = {
"01-flex-container": ('<h2>1. Flex Container</h2><p>Parent with display:flex becomes flex container.</p><div class="container"><div class="box">Box 1</div><div class="box">Box 2</div><div class="box">Box 3</div></div>', '.container{display:flex;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;margin:10px;border:2px solid blue;font-weight:bold}'),
"02-flex-items": ('<h2>2. Flex Items</h2><p>Direct children are flex items.</p><div class="container"><div class="box">Item 1</div><div class="box">Item 2</div><div class="box">Item 3</div></div>', '.container{display:flex;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;margin:10px;border:2px solid blue}'),
"03-main-axis": ('<h2>3. Main Axis</h2><p>Main axis is horizontal by default.</p><div class="container"><div class="box">1</div><div class="box">2</div><div class="box">3</div></div>', '.container{display:flex;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;margin:10px;border:2px solid blue}'),
"04-cross-axis": ('<h2>4. Cross Axis</h2><p>Cross axis is vertical.</p><div class="container"><div class="box">1</div><div class="box">2</div><div class="box">3</div></div>', '.container{display:flex;height:200px;align-items:flex-start;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;margin:10px;border:2px solid blue}'),
"05-flex-direction": ('<h2>5. Flex Direction</h2><p>Controls direction of main axis.</p><div class="container"><div class="box">1</div><div class="box">2</div><div class="box">3</div></div>', '.container{display:flex;flex-direction:column;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:20px;margin:5px;border:2px solid blue}'),
"06-justify-content": ('<h2>6. Justify Content</h2><p>Aligns on main axis.</p><div class="container"><div class="box">1</div><div class="box">2</div><div class="box">3</div></div>', '.container{display:flex;justify-content:space-between;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;border:2px solid blue}'),
"07-align-items": ('<h2>7. Align Items</h2><p>Aligns on cross axis.</p><div class="container"><div class="box">1</div><div class="box">2</div><div class="box">3</div></div>', '.container{display:flex;align-items:center;height:200px;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;margin:10px;border:2px solid blue}'),
"08-flex-wrap": ('<h2>8. Flex Wrap</h2><p>Allows wrapping.</p><div class="container"><div class="box">1</div><div class="box">2</div><div class="box">3</div><div class="box">4</div><div class="box">5</div><div class="box">6</div></div>', '.container{display:flex;flex-wrap:wrap;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;margin:10px;border:2px solid blue;width:100px}'),
"09-gap": ('<h2>9. Gap</h2><p>Gap between items.</p><div class="container"><div class="box">1</div><div class="box">2</div><div class="box">3</div></div>', '.container{display:flex;gap:30px;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;border:2px solid blue}'),
"10-flex-grow": ('<h2>10. Flex Grow</h2><p>Item grows to fill space.</p><div class="container"><div class="box">1</div><div class="box grow">2 Grow</div><div class="box">3</div></div>', '.container{display:flex;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;margin:5px;border:2px solid blue}.grow{flex-grow:1;background:orange}'),
"11-flex-shrink": ('<h2>11. Flex Shrink</h2><p>Item shrinks if needed.</p><div class="container"><div class="box shrink">1 Shrink</div><div class="box">2</div><div class="box">3</div></div>', '.container{display:flex;background:#eee;padding:20px;border:3px solid black}.box{background:lightblue;padding:30px;margin:5px;border:2px solid blue;width:300px}.shrink{flex-shrink:2;background:orange}'),
}
for folder,(body,css) in data.items():
    os.makedirs(folder, exist_ok=True)
    html = f"<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>{folder}</title><link rel='stylesheet' href='style.css'></head><body>{body}</body></html>"
    open(os.path.join(folder,'index.html'),'w',encoding='utf-8').write(html)
    open(os.path.join(folder,'style.css'),'w',encoding='utf-8').write(f"body{{font-family:sans-serif}}{css}")
print("All 11 folders completed!")